---
# tasks file for nginx
- name: install nginx on the webserver
  ansible.builtin.yum:
    name: nginx
    state: present


- name: ensure nginx is started and enabled
  ansible.builtin.service:
     name: nginx
     state: started 
     enabled: yes

- name: Deploy static website
  command: echo "Welcome to Mukhtar's hub" > /var/www/html