---
- hosts: todo
  become: yes
  tasks:
    - name: add dnf utils,epel and remi repository
      ansible.builtin.yum:
        name:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
          - https://rpms.remirepo.net/enterprise/remi-release-8.rpm
          - dnf-utils
        disable_gpg_check: yes

    - name: install httpd on the web server
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: ensure httpd is started and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: enable PHP 7.4 Remi module and install PHP 7.4 
      ansible.builtin.yum:
        name: 
          - php:remi-7.4
          - php 
          - php-mysqlnd
          - php-gd 
          - php-curl
          - unzip
          - php-common
          - php-mbstring
          - php-opcache
          - php-intl
          - php-xml
          - php-fpm
          - php-json
        # enablerepo: php:remi-7.4
        state: present
    
    - name: ensure php-fpm is started and enabled
      ansible.builtin.service:
        name: php-fpm
        state: started 
        enabled: yes

    - name: download the php-todo artifact
      get_url:
        url: http://3.238.253.40:8082/artifactory/Proj-14/php-todo
        dest: /home/ec2-user
        url_username: admin
        url_password: APABGzk2xjsDanG4mbxN3ZffMRS

    - name: unzip the downloaded artifact
      ansible.builtin.unarchive:
       src: /home/ec2-user/php-todo
       dest: /home/ec2-user/
       remote_src: yes

    - name: deploy the code to apache web root directory
      ansible.builtin.copy:
        src: /home/ec2-user/php-todo
        dest: /var/www/html
        force: yes
        remote_src: yes

    - name: remove apache default page
      ansible.builtin.file:
        path: /etc/httpd/httpd.conf/welcome.conf
        state: absent

    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted


          