---
- name: install apache
  become: true
  ansible.builtin.yum:
    name: httpd
    state: present

- name: install git
  become: true
  ansible.builtin.yum:
    name: git
    state: present

- name: clone tooling repository
  become: true
  ansible.builtin.git:
    repo: https://github.com/Babbexx-22/tooling_.git.
    dest: /var/www/tooling
    force: yes

- name: copy html content from /var/www/tooling/html/ to /var/www
  become: true
  command: cp -r /var/www/tooling/html/ /var/www/

- name: start httpd if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html
  become: true
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent